version: '2'
services:
  backend:
    image: 'python:3.13-rc-slim'
    tty: true
    ports:
      - '8881:8881'
    volumes:
      - 'C:\Users\leon_\Documents\Interactive-Neighborhood-Map\backend\backend:/usr/src/app/backend'
  db:
    image: 'mongo:7'
    volumes:
      - '.\data_db:/data/db'
    ports:
      - '8882:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
