FROM continuumio/miniconda3
COPY conda_config.yml /tmp
RUN apt update
RUN apt install sqlite3 wget -y

# load conda env
RUN conda init bash
RUN conda env create -f /tmp/conda_config.yml
RUN echo "conda activate main_env" >> ~/.bashrc
