FROM python:3.13-rc-slim-bookworm
COPY conda_config.yml /tmp
RUN cat /tmp/conda_config.yml
RUN apt update
RUN apt install sqlite3 wget -y

# install miniconda
RUN mkdir -p ~/miniconda3
WORKDIR ~/miniconda3
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
RUN bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
RUN rm -rf ~/miniconda3/miniconda.sh

# load conda env
RUN ~/miniconda3/bin/conda init bash
RUN . ~/.bashrc && conda env create -f /tmp/conda_config.yml
RUN echo "conda activate main_env" >> ~/.bashrc
