version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - 3500:3000
    volumes:
     - grafana-storage:/var/lib/grafana
    environment:
     - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
     - GF_SECURITY_COOKIE_SAMESITE=strict
     - GF_SECURITY_ALLOW_EMBEDDING=true
     - GF_SECURITY_ADMIN_USER=true
     - GF_SECURITY_ADMIN_PASSWORD=
     - GF_SECURITY_ADMIN_EMAIL=
     - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
     - GF_SERVER_ROOT_URL=http://localhost:3500/
     - GF_AUTH.ANONYMOUS_ENALBED=true
     - GF_AUTH.ANONYMOUS_ORG_NAME=Main Org.
     - GF_AUTH.ANONYMOUS_ORG_ROLE=Viewer
volumes:
  grafana-storage: {}